### ISSUE TITLE
How to create a Block Type as opposed to a simple block

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/conditional_content_block#3]
In theory, I can create many blocks with this module. BUT, all the blocks share the same content. 

How do I store unique content for each block?

Should each block have it's own config file or do I store all the content for blocks generated by this module in one config file?

(Assuming I should be using config at all).

**Comment by docwilmot** [comment]
If you dont use a config file, then all blocks would have unique content.

**Comment by stpaultim** [comment]
Actually, I'm going to close this issue as well - since I've already implemented the advice of @docwilmot and simply taken the content out of config. I can now create multiple different blocks of this type.
